spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fruit_traceability
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 300000
      pool-name: FruitTraceabilityPool

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

  mvc:
    cors:
      allowed-origins: http://localhost:5173
      allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
      allowed-headers:
        - Authorization
        - Content-Type
        - Accept
        - Origin
        - Access-Control-Request-Method
        - Access-Control-Request-Headers
        - Access-Control-Allow-Origin
        - Access-Control-Allow-Credentials
      allow-credentials: true
      exposed-headers:
        - Authorization
        - Access-Control-Allow-Origin
        - Access-Control-Allow-Credentials
      max-age: 3600

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  expiration: 86400000

server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always

logging:
  level:
    root: INFO
    com.traceability: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
